#  Scrutinizer Configuration File

tools:
  external_code_coverage: false

  php_sim:
    enabled: true
    min_mass: 50

  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php
    excluded_dirs: {  }

  php_analyzer:
    enabled: true
    extensions:
      - php
    dependency_paths: {  }
    path_configs: {  }

  php_changetracking:
    enabled: true
    bug_patterns:
      - '\bfix(?:es|ed)?\b'
    feature_patterns:
      - '\badd(?:s|ed)?\b'
      - '\bimplement(?:s|ed)?\b'

  php_hhvm:
    enabled: true
    command: hhvm
    extensions:
      - php
    path_configs: {  }

before_commands: {  }
after_commands: {  }
artifacts: {  }
build_failure_conditions: {  }
